version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "docker"
    directory: "/tutorcairn/templates/cairn/build/cairn-clickhouse"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "docker"
    directory: "/tutorcairn/templates/cairn/build/cairn-superset"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
